#! /bin/sh
INTERFACE=$1
HOSTNAMEFILE="/etc/hostname"
HOSTNAMEBKP="/etc/hostname.bkp"
#This script will randomize your mac address and hostname to mimic other devices on the network
if [ $# -eq 0 ]; then
	echo "Missing an argument. Please run './hostRandomizer [interface]' i.e., './hostRandomizer eth0' OR './hostRandomizer eth0 revert' to revert back to the original configuration."
	exit 1
fi
if [ $2 = "revert" ]; then
	echo "Reverting to original configuration"
	macchanger -p $INTERFACE
	if [ ! -f $HOSTNAMEBKP ]; then
		echo "[-] ERROR: Missing hostname backup file. Are you sure you have run hostRandomizer previously?"
	else
		mv $HOSTNAMEBKP $HOSTNAMEFILE
		service hostname.sh
		echo "Your hostname has been reverted to:"
		hostname
	fi
else
	#MAC Address Change (requires macchanger)
	ifconfig $INTERFACE down
	macchanger -r $INTERFACE
	echo "Your MAC address has been changed."
	ifconfig $INTERFACE up
	
	#Hostname Change (This is permenant until revert is run)
	# backup original hostname file so we can revert later
	if [ -f $HOSTNAMEBKP ]; then
		echo "[-] ERROR: Hostname backup file exists (/etc/hostname.bkp). If you have run hostRandomizer, please use the revert option before running again."
	else
		cp $HOSTNAMEFILE $HOSTNAMEBKP
	fi
	#Randomize hostname
	DEVICE=$(shuf -n 1 hosts1)
	NUMBER=$(cat /dev/urandom | tr -dc '0-9' | fold -w 5 | head -n 1)
	echo $DEVICE-$NUMBER > $HOSTNAMEFILE
	service hostname.sh
	echo "Your new hostname is:"
	hostname
fi

